[profile.default]
solc = "0.8.17"
optimizer = true
via_ir = true
optimizer_runs = 1000000
no_match_path = "*/integration/*"
fuzz_runs = 10000
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]

[profile.integration]
no_match_path = ""
match_path = "*/integration/*"


[rpc_endpoints]
localhost = "http://localhost:8545"
ethereum = "https://eth.llamarpc.com"
ronin-mainnet = "https://api.roninchain.com/rpc"
goerli = "https://ethereum-goerli.publicnode.com"
ronin-testnet = "https://saigon-archive.roninchain.com/rpc"
